[2024-05-12 00:01:53,386: INFO: main: Welcome to my custom log:]
[2024-05-12 21:19:14,022: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-12 21:19:14,026: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-12 21:19:14,027: INFO: common: created directory at artifacts:]
[2024-05-12 21:19:14,028: INFO: common: created directory at artifacts/data_ingestion:]
[2024-05-12 21:20:29,403: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-12 21:20:29,404: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-12 21:20:29,405: INFO: common: created directory at artifacts:]
[2024-05-12 21:20:29,406: INFO: common: created directory at artifacts/data_ingestion:]
[2024-05-12 21:21:45,334: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-12 21:21:45,336: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-12 21:21:45,337: INFO: common: created directory at artifacts:]
[2024-05-12 21:21:45,338: INFO: common: created directory at artifacts/data_ingestion:]
[2024-05-12 21:26:18,340: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-12 21:26:18,342: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-12 21:26:18,343: INFO: common: created directory at artifacts:]
[2024-05-12 21:26:18,344: INFO: common: created directory at artifacts/data_ingestion:]
[2024-05-12 21:26:26,203: INFO: 1264318398: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11621297
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "9078d58f18846f90224572e08b05699040bf7dc5c85c1618a8eac33ea6b63eec"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 481C:37C1BA:5FBB77:7D7249:6640E6A2
Accept-Ranges: bytes
Date: Sun, 12 May 2024 15:56:19 GMT
Via: 1.1 varnish
X-Served-By: cache-maa10222-MAA
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1715529379.290974,VS0,VE708
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 537cfdd6a93d21bca3cd885681f545d53196debb
Expires: Sun, 12 May 2024 16:01:19 GMT
Source-Age: 0

:]
[2024-05-12 21:47:49,608: INFO: main: >>>>> stage Data Ingestion stage started <<<<<:]
[2024-05-12 21:47:49,609: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-12 21:47:49,610: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-12 21:47:49,610: INFO: common: created directory at artifacts:]
[2024-05-12 21:47:49,610: INFO: common: created directory at artifacts/data_ingestion:]
[2024-05-12 21:47:50,246: ERROR: main: HTTP Error 404: Not Found:]
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    obj.main()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/components/data_ingestion.py", line 15, in download_file
    filename, headers = request.urlretrieve(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2024-05-12 21:48:20,383: INFO: main: >>>>> stage Data Ingestion stage started <<<<<:]
[2024-05-12 21:48:20,384: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-12 21:48:20,384: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-12 21:48:20,384: INFO: common: created directory at artifacts:]
[2024-05-12 21:48:20,384: INFO: common: created directory at artifacts/data_ingestion:]
[2024-05-12 21:48:20,406: ERROR: main: <urlopen error [Errno -2] Name or service not known>:]
Traceback (most recent call last):
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/http/client.py", line 1418, in connect
    super().connect()
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 10, in <module>
    obj.main()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/components/data_ingestion.py", line 15, in download_file
    filename, headers = request.urlretrieve(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
[2024-05-12 21:48:43,831: INFO: main: >>>>> stage Data Ingestion stage started <<<<<:]
[2024-05-12 21:48:43,832: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-12 21:48:43,832: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-12 21:48:43,833: INFO: common: created directory at artifacts:]
[2024-05-12 21:48:43,833: INFO: common: created directory at artifacts/data_ingestion:]
[2024-05-12 21:48:44,254: ERROR: main: HTTP Error 404: Not Found:]
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    obj.main()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/components/data_ingestion.py", line 15, in download_file
    filename, headers = request.urlretrieve(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2024-05-12 21:48:46,567: INFO: main: >>>>> stage Data Ingestion stage started <<<<<:]
[2024-05-12 21:48:46,568: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-12 21:48:46,568: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-12 21:48:46,568: INFO: common: created directory at artifacts:]
[2024-05-12 21:48:46,568: INFO: common: created directory at artifacts/data_ingestion:]
[2024-05-12 21:48:46,985: ERROR: main: HTTP Error 404: Not Found:]
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    obj.main()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/components/data_ingestion.py", line 15, in download_file
    filename, headers = request.urlretrieve(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2024-05-12 21:48:56,228: INFO: main: >>>>> stage Data Ingestion stage started <<<<<:]
[2024-05-12 21:48:56,229: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-12 21:48:56,230: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-12 21:48:56,230: INFO: common: created directory at artifacts:]
[2024-05-12 21:48:56,230: INFO: common: created directory at artifacts/data_ingestion:]
[2024-05-12 21:48:56,546: ERROR: main: HTTP Error 404: Not Found:]
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    obj.main()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "/home/technopath/Desktop/Project/Chicken-Disease-Classification/src/cnnClassifier/components/data_ingestion.py", line 15, in download_file
    filename, headers = request.urlretrieve(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/technopath/miniconda3/envs/.chicken/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2024-05-12 21:49:21,467: INFO: main: >>>>> stage Data Ingestion stage started <<<<<:]
[2024-05-12 21:49:21,468: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2024-05-12 21:49:21,468: INFO: common: yaml file: params.yaml loaded successfully:]
[2024-05-12 21:49:21,468: INFO: common: created directory at artifacts:]
[2024-05-12 21:49:21,468: INFO: common: created directory at artifacts/data_ingestion:]
[2024-05-12 21:49:28,688: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11621297
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "9078d58f18846f90224572e08b05699040bf7dc5c85c1618a8eac33ea6b63eec"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 481C:37C1BA:5FBB77:7D7249:6640E6A2
Accept-Ranges: bytes
Date: Sun, 12 May 2024 16:19:22 GMT
Via: 1.1 varnish
X-Served-By: cache-maa10226-MAA
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1715530762.143648,VS0,VE270
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 3f0316195e762d3f56c4ca835f89c99b4503194b
Expires: Sun, 12 May 2024 16:24:22 GMT
Source-Age: 0

:]
[2024-05-12 21:49:28,770: INFO: main: >>>>> stage Data Ingestion stage completed <<<<<

x=============x:]
